use crate::models::VaultData;

pub fn generate_env(vault: &VaultData, project_name: &str) -> Result<String, String> {
    let project = vault
        .projects
        .get(project_name)
        .ok_or_else(|| format!("Project '{}' not registered.", project_name))?;

    let mut lines = vec![
        format!("# Generated by pqvault for project: {}", project_name),
        String::new(),
    ];

    let mut sorted_keys: Vec<&String> = project.keys.iter().collect();
    sorted_keys.sort();

    for key_name in &sorted_keys {
        if let Some(secret) = vault.secrets.get(key_name.as_str()) {
            lines.push(format!("{}={}", key_name, secret.value));
        } else if let Some(val) = project.env_extras.get(key_name.as_str()) {
            lines.push(format!("{}={}", key_name, val));
        }
    }

    // Add extras not in keys list
    let mut sorted_extras: Vec<(&String, &String)> = project
        .env_extras
        .iter()
        .filter(|(k, _)| !project.keys.contains(k))
        .collect();
    sorted_extras.sort_by_key(|(k, _)| k.to_string());

    for (key_name, value) in sorted_extras {
        lines.push(format!("{}={}", key_name, value));
    }

    lines.push(String::new());
    Ok(lines.join("\n"))
}
